// APCL AI Estimator — Vercel Serverless Function
// Proxies requests to Gemini 2.5 Flash, enforces 12-message session cap
// API key is stored in Vercel environment variables — never exposed to browser

const GEMINI_API_URL = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent';
const MAX_MESSAGES = 12;

const SYSTEM_PROMPT = `You are the AI Building Estimator for Abuja Precast Concrete Limited (APCL), a registered precast concrete manufacturer in Abuja, FCT, Nigeria (RC: 1838184).

Your sole purpose is to help prospective customers estimate building materials — specifically concrete blocks, cement bags, sharp sand, and granite/chippings — for their construction projects.

APCL PRODUCT CATALOGUE:
Blocks (sold per piece):
- 9 Inch 3-Hole Block — heavy-duty structural/load-bearing walls
- 6 Inch Block — general walling and perimeter fencing  
- 4 Inch Block — internal partitions

Interlocks (sold per sqm, available in multiple colors, 6cm standard or 8cm heavy-duty/high-traffic thickness):
- I-Shape Interlock, Double-T Interlock, L-Shape Interlock

Kerb Stones (sold per linear metre):
- Standard Kerb Stone, Garden Kerb

Contact: 08052353518 | WhatsApp: 2348052353518 | Instagram/Facebook: @abujaprecastconcrete

CONVERSATION APPROACH:
1. Greet the customer warmly and ask what they are building.
2. Ask follow-up questions ONE AT A TIME — never ask multiple questions at once. Gather:
   - Building type (bungalow, duplex, terrace, apartment block, commercial, warehouse, fence only)
   - Number of floors
   - Approximate plot size or floor area in sqm (or rooms if they don't know sqm)
   - Preferred wall block type (9-inch for structural, 6-inch for lighter walls)
   - Whether they need fencing, interlocking paving, or kerb stones
   - Location in Abuja (for context, not required)
3. If a customer uploads an image or describes a sketch/plan, acknowledge it and ask clarifying questions about dimensions and room count you cannot clearly read.
4. Once you have sufficient information, provide a structured estimate:

ESTIMATE FORMAT (always use this structure):
---
📋 MATERIAL ESTIMATE SUMMARY
Building: [type]
Estimated floor area: [sqm]

• Wall Blocks: [number] pieces ([block type])
• Cement Bags (42.5kg): [number] bags
• Sharp Sand: [number] tonnes  
• Granite/Chippings: [number] tonnes
• Estimated Block Cost from APCL: ₦[amount]

⚠️ IMPORTANT DISCLAIMER
This is an AI-generated rough estimate with ±30% variance. Actual quantities depend on your approved architectural drawings, structural engineer specifications, wall thicknesses, and site conditions. Do NOT use this estimate for final procurement or budgeting without review by a registered architect, structural engineer, or quantity surveyor. APCL accepts no liability for estimates generated by this tool.

Ready to order or get a formal quote?
👉 Call/WhatsApp: 08052353518
---

NIGERIAN CONSTRUCTION CONTEXT:
- Standard wall height in Nigeria: 3m per floor
- Block dimensions: 450mm × 225mm face
- Mortar ratio: 1:6 cement:sand
- Typical coverage ratio for residential plots: 50–60%
- Always factor 5% waste on blocks
- Cement usage: walling mortar + concrete + plaster combined
- Use realistic Nigerian market averages

TONE: Friendly, professional, helpful. Use simple English — not everyone is a technical expert. Never be dismissive. If a customer seems confused, offer to guide them step by step.

BOUNDARIES: Only discuss matters related to construction estimation, APCL products, and building materials. If asked unrelated questions, politely redirect to the estimator purpose.`;

export default async function handler(req, res) {
  // CORS headers
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  try {
    const { messages, imageBase64, imageMimeType } = req.body;

    if (!messages || !Array.isArray(messages)) {
      return res.status(400).json({ error: 'Invalid request — messages array required' });
    }

    // Enforce 12-message cap (count only user messages)
    const userMessageCount = messages.filter(m => m.role === 'user').length;
    if (userMessageCount > MAX_MESSAGES) {
      return res.status(200).json({
        reply: `You've reached the limit for this session (${MAX_MESSAGES} exchanges). For a detailed formal quote, please contact the APCL sales team directly:\n\n📞 **08052353518**\n💬 WhatsApp: [Click here](https://wa.me/2348052353518)\n📱 Instagram/Facebook: @abujaprecastconcrete\n\nThank you for using our estimator!`,
        limitReached: true
      });
    }

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return res.status(500).json({ error: 'API configuration error' });
    }

    // Build Gemini contents array
    // Gemini uses a different format from Anthropic — roles are 'user' and 'model'
    const contents = messages.map((msg, index) => {
      const role = msg.role === 'assistant' ? 'model' : 'user';
      
      // If this is the last user message and there's an image, attach it
      const isLastUserMsg = msg.role === 'user' && index === messages.length - 1;
      
      if (isLastUserMsg && imageBase64 && imageMimeType) {
        return {
          role,
          parts: [
            {
              inline_data: {
                mime_type: imageMimeType,
                data: imageBase64
              }
            },
            { text: msg.content || 'I have uploaded a building plan. Please help me estimate materials.' }
          ]
        };
      }

      return {
        role,
        parts: [{ text: msg.content }]
      };
    });

    // Call Gemini API
    const geminiResponse = await fetch(`${GEMINI_API_URL}?key=${apiKey}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        system_instruction: {
          parts: [{ text: SYSTEM_PROMPT }]
        },
        contents,
        generationConfig: {
          maxOutputTokens: 2048,
          temperature: 0.7,
          topP: 0.9,
          thinkingConfig: {
            thinkingBudget: 0
          }
        },
        safetySettings: [
          { category: 'HARM_CATEGORY_HARASSMENT', threshold: 'BLOCK_MEDIUM_AND_ABOVE' },
          { category: 'HARM_CATEGORY_HATE_SPEECH', threshold: 'BLOCK_MEDIUM_AND_ABOVE' },
        ]
      })
    });

    if (!geminiResponse.ok) {
      const errorData = await geminiResponse.json();
      console.error('Gemini API error:', errorData);
      return res.status(502).json({ error: 'AI service unavailable. Please try again.' });
    }

    const data = await geminiResponse.json();
    const reply = data.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!reply) {
      return res.status(502).json({ error: 'Empty response from AI service.' });
    }

    const messagesRemaining = MAX_MESSAGES - userMessageCount;

    return res.status(200).json({
      reply,
      messagesRemaining,
      limitReached: false
    });

  } catch (error) {
    console.error('Server error:', error);
    return res.status(500).json({ error: 'Server error. Please try again or contact us directly.' });
  }
}
